# Simple test configuration

[data]
output_dir = "output"
max_users = 3  # Process 3 users
min_readings = 2  # At least 2 readings per user
user_offset = 0  # No offset
export_database = true

[processing]
extreme_threshold = 0.20
kalman_cleanup_threshold = 4.0

[kalman]
initial_variance = 0.361
transition_covariance_weight = 0.0160
transition_covariance_trend = 0.0001
observation_covariance = 3.490
reset_gap_days = 30
questionnaire_reset_days = 10

[visualization]
enabled = true
mode = "interactive"
use_diagnostic = false  # Use standard dashboard

[logging]
progress_interval = 1000
timestamp_format = "test_no_date"
verbose = false

[quality_scoring]
enabled = false
threshold = 0.6