# Test configuration for visualization features

[data]
csv_file = "./data/test_sample.csv"
output_dir = "test_output_real"
max_users = 3
user_offset = 0  # No offset for testing
min_readings = 10  # Lower threshold for test data
min_date = "2015-01-01"
max_date = "2025-09-05"
export_database = true

[processing]
extreme_threshold = 0.20
kalman_cleanup_threshold = 4.0

[kalman]
initial_variance = 0.361
transition_covariance_weight = 0.0160
transition_covariance_trend = 0.0001
observation_covariance = 3.490
reset_gap_days = 30
questionnaire_reset_days = 10

[visualization]
enabled = true
mode = "interactive"
use_enhanced = true
verbosity = "normal"

[visualization.markers]
show_source_icons = true
show_reset_markers = true
reset_marker_color = "#FF6600"
reset_marker_style = "annotation"

[visualization.rejection]
show_severity_colors = true
group_by_severity = true

[adaptive_noise]
enabled = true
default_multiplier = 1.5

[logging]
progress_interval = 10000
timestamp_format = "test_no_date"

[quality_scoring]
enabled = true
threshold = 0.6
use_harmonic_mean = true

[quality_scoring.component_weights]
safety = 0.35
plausibility = 0.25
consistency = 0.25
reliability = 0.15