# Test configuration for enhanced visualization

[data]
csv_file = "./data/test_multi_user.csv"
output_dir = "test_enhanced_data"
max_users = 20
user_offset = 0  # Start from first user
min_readings = 2  # Lower threshold for test data
min_date = "2024-01-01"
max_date = "2025-12-31"
export_database = true

[processing]
extreme_threshold = 0.20
kalman_cleanup_threshold = 4.0

[kalman]
initial_variance = 0.361
transition_covariance_weight = 0.0160
transition_covariance_trend = 0.0001
observation_covariance = 3.490
reset_gap_days = 30
questionnaire_reset_days = 10

[visualization]
enabled = true
mode = "interactive"
use_diagnostic = true
use_enhanced = true
verbosity = "normal"
theme = "plotly_white"

[adaptive_noise]
enabled = true
default_multiplier = 1.5

[logging]
progress_interval = 10
timestamp_format = "test_no_date"

[quality_scoring]
enabled = true
threshold = 0.6
use_harmonic_mean = true

[quality_scoring.component_weights]
safety = 0.35
plausibility = 0.25
consistency = 0.25
reliability = 0.15