# Weight Stream Processor Configuration

[data]
# CSV file to process
csv_file = "./data/2025-09-05_optimized.csv"

# Output directory for results and visualizations
output_dir = "output"

# Maximum number of users to process (0 = unlimited)
max_users = 0

# Number of users to skip at the beginning (useful for resuming or testing)
user_offset = 0

[processing]
# Minimum readings needed to initialize Kalman filter
min_init_readings = 5

# Weight validation limits (kg)
min_weight = 30.0
max_weight = 400.0

# Maximum daily change allowed (as fraction)
max_daily_change = 0.03

# Extreme deviation threshold for rejecting measurements
extreme_threshold = 0.30

[kalman]
# Initial variance scaling
initial_variance = 1.0

# Process noise covariance matrix values
transition_covariance_weight = 0.5
transition_covariance_trend = 0.01

# Observation noise
observation_covariance = 1.0

# Reset threshold - days without data before resetting state
reset_gap_days = 30

[visualization]
# Maximum number of user visualizations to generate
max_visualizations = 10

# Minimum data points required for visualization
min_data_points = 20

# Dashboard settings
dashboard_dpi = 100
dashboard_figsize = [16, 10]

# Moving average window for trend analysis
moving_average_window = 7

[logging]
# Progress update interval (rows)
progress_interval = 10000

# Date format for output files
timestamp_format = "%Y%m%d_%H%M%S"