# Weight Stream Processor Configuration - CLEANED VERSION

[data]
# Input/output settings
# csv_file = "./data/2025-09-05_optimized.csv"  # Input CSV file path (preprocessed with scripts/preprocess_csv.py)
csv_file = "./data/2025-09-05_nocon.csv" # no connective health data
output_dir = "output"  # Output directory for results
max_users = 100  # Maximum number of users to process (0 = all)
user_offset = 0  # Skip this many users at start
min_readings = 20  # Minimum readings required per user
min_date = "2015-01-01"  # Earliest date to process (YYYY-MM-DD)
max_date = "2026-01-01"  # Latest date to process (YYYY-MM-DD)
export_database = true  # Export results to database file

[processing]
# Core processing parameters
extreme_threshold = 0.20  # Maximum deviation from Kalman prediction (0.20 = 20%)

[kalman]
# Kalman filter parameters (optimized 2025-09-13)
initial_variance = 0.361  # Initial state uncertainty
transition_covariance_weight = 0.0160  # Process noise for weight
transition_covariance_trend = 0.0001  # Process noise for trend
observation_covariance = 3.490  # Measurement noise
reset_gap_days = 30  # Days before resetting Kalman state
questionnaire_reset_days = 10  # Days for questionnaire source reset

[visualization]
# Display settings
enabled = true  # Enable visualization output
use_enhanced = true  # Use enhanced dashboard with quality insights
verbosity = "normal"  # Verbosity level: "silent" | "minimal" | "normal" | "verbose"

[visualization.markers]
# Marker display configuration
show_source_icons = true  # Different marker shapes per source type
show_source_legend = true  # Display legend for source types
show_reset_markers = true  # Display reset event annotations
reset_marker_color = "#FF6600"  # Color for reset markers (orange)
reset_marker_opacity = 0.2  # Transparency of reset lines (0-1)
reset_marker_width = 1  # Width of reset lines in pixels
reset_marker_style = "dot"  # Line style: "solid" | "dash" | "dot"

[visualization.rejection]
# Rejection display configuration
show_severity_colors = true  # Color intensity shows rejection severity
group_by_severity = true  # Separate legend entries per severity level

[adaptive_noise]
# Adaptive noise configuration for source-specific processing
enabled = true  # Enable adaptive noise based on source type
default_multiplier = 1.5  # Default noise multiplier for unknown sources

[logging]
# Logging configuration
progress_interval = 10000  # Show progress every N rows
timestamp_format = "test_no_date"  # Format for output timestamps

[quality_scoring]
# Quality scoring system configuration
enabled = true  # Enable quality scoring system
threshold = 0.6  # Minimum score for acceptance (0-1)
use_harmonic_mean = true  # Use harmonic mean (penalizes low scores)

[quality_scoring.component_weights]
# Component weights (must sum to 1.0)
safety = 0.35        # Weight for physiological limits check
plausibility = 0.25  # Weight for statistical deviation check
consistency = 0.25   # Weight for rate of change check
reliability = 0.15   # Weight for source reliability check
