[data]
csv_file = "./data/2025-09-05_nocon.csv"
output_dir = "output"
max_users = 20
user_offset = 0
min_readings = 20
min_date = "2015-01-01"
max_date = "2026-01-01"
export_database = true

[processing]
extreme_threshold = 0.15

[kalman]
initial_variance = 0.361
transition_covariance_weight = 0.016
transition_covariance_trend = 0.0001
observation_covariance = 3.4

[visualization]
enabled = true
use_enhanced = true
verbosity = "normal"

[adaptive_noise]
enabled = true
default_multiplier = 1.5

[retrospective]
enabled = true
buffer_hours = 1
trigger_mode = "time_based"
max_buffer_measurements = 100
state_history_limit = 100

[logging]
progress_interval = 10000
timestamp_format = "test_no_date"

[quality_scoring]
enabled = true
use_harmonic_mean = true
threshold = 0.6

[visualization.markers]
show_source_icons = true
show_source_legend = true
show_reset_markers = false
reset_marker_color = "#FF6600"
reset_marker_opacity = 0.2
reset_marker_width = 1
reset_marker_style = "dot"

[visualization.rejection]
show_severity_colors = true
group_by_severity = false

[visualization.reset]
show_reset_lines = false
show_gap_regions = false
show_gap_labels = false
reset_line_color = "#FF6600"
reset_line_style = "dash"
reset_line_width = 2
gap_region_color = "#F0F0F0"
gap_region_opacity = 0.5
gap_region_pattern = "diagonal"
show_transition_markers = false
transition_marker_size = 10

[retrospective.outlier_detection]
iqr_multiplier = 1.5
z_score_threshold = 3.0
temporal_max_change_percent = 0.5
min_measurements_for_analysis = 2

[retrospective.safety]
max_processing_time_seconds = 60
require_rollback_confirmation = false
preserve_immediate_results = true

[quality_scoring.component_weights]
safety = 0.35
plausibility = 0.25
consistency = 0.25
reliability = 0.15

[kalman.reset.initial]
enabled = true
initial_variance_multiplier = 10
weight_noise_multiplier = 50
trend_noise_multiplier = 50
observation_noise_multiplier = 20
adaptation_measurements = 10
adaptation_days = 10
adaptation_decay_rate = 2.5
quality_acceptance_threshold = 0.45
quality_safety_weight = 0.45
quality_plausibility_weight = 0.1
quality_consistency_weight = 0.1
quality_reliability_weight = 0.35

[kalman.reset.hard]
enabled = true
gap_threshold_days = 30
initial_variance_multiplier = 3
weight_noise_multiplier = 5
trend_noise_multiplier = 50
observation_noise_multiplier = 0.7
adaptation_measurements = 10
adaptation_days = 7
adaptation_decay_rate = 2.5
quality_acceptance_threshold = 0.45
quality_safety_weight = 0.45
quality_plausibility_weight = 0.1
quality_consistency_weight = 0.1
quality_reliability_weight = 0.35

[kalman.reset.soft]
enabled = true
min_weight_change_kg = 5
cooldown_days = 3
trigger_sources = [ "questionnaire", "patient-upload", "care-team-upload",]
initial_variance_multiplier = 2
weight_noise_multiplier = 5
trend_noise_multiplier = 20
observation_noise_multiplier = 0.7
adaptation_measurements = 15
adaptation_days = 10
adaptation_decay_rate = 2.5
quality_acceptance_threshold = 0.4
quality_safety_weight = 0.4
quality_plausibility_weight = 0.15
quality_consistency_weight = 0.15
quality_reliability_weight = 0.3
