# Weight Stream Processor Configuration

[data]
# CSV file to process
csv_file = "./data/2025-09-05_optimized.csv"

# Output directory for results and visualizations
output_dir = "output"

# Maximum number of users to process (0 = unlimited)
max_users = 20

# Number of users to skip at the beginning (useful for resuming or testing)
user_offset = 400

# Minimum number of readings required to process a user (0 = no minimum)
# Users with fewer readings are skipped and don't count towards max_users
min_readings = 20



# List of specific user IDs to process
test_users = [
  "0040872d-333a-4ace-8c5a-b2fcd056e65a", # user with extremely noisy data
  "1e87d3ab-20b1-479d-ad4d-8986e1af38da", # long gap
  "0093a653-476b-4401-bbec-33a89abc2b18", # User with sparse historical data
  "4d5054c4-2492-4cd8-a15c-53381fb6bd49", # spiky data
]

# 0040872d-333a-4ace-8c5a-b2fcd056e65a - user with extremely noisy data

[processing]
# min_init_readings = 10  # No longer used - immediate processing enabled

# Weight validation limits (kg)
min_weight = 30.0
max_weight = 400.0

# Maximum daily change allowed (as fraction)
max_daily_change = 0.05  # was 0.03

# Extreme deviation threshold for rejecting measurements
extreme_threshold = 0.20  # was 0.30

# Kalman-guided cleanup threshold (kg)
# Measurements more than this far from Kalman prediction are rejected during daily cleanup
kalman_cleanup_threshold = 4.0

[kalman]
# Initial variance scaling
initial_variance = 0.5  # was 1.0

# Process noise covariance matrix values
transition_covariance_weight = 0.05  # was 0.5
transition_covariance_trend = 0.0005  # was 0.01

# Observation noise
observation_covariance = 1.5  # was 1.0

# Reset threshold - days without data before resetting state
reset_gap_days = 30

[visualization]
# Dashboard settings
dashboard_dpi = 100
dashboard_figsize = [16, 10]

# Moving average window for trend analysis
moving_average_window = 7

# Time range for cropped views (in months)
# Shows the last N months of data for each user
cropped_months = 9

[logging]
# Progress update interval (rows)
progress_interval = 10000

# Date format for output files
# timestamp_format = "%Y%m%d_%H%M%S"
timestamp_format = "test_no_date"
