# Weight Stream Processor Configuration - CLEANED VERSION

[data]
# Input/output settings
# csv_file = "./data/2025-09-05_optimized.csv"  # Input CSV file path (preprocessed with scripts/preprocess_csv.py)
csv_file = "./data/2025-09-05_nocon.csv" # no connective health data
output_dir = "output"  # Output directory for results
max_users = 200  # Maximum number of users to process (0 = all)
user_offset = 0  # Skip this many users at start
min_readings = 20  # Minimum readings required per user
min_date = "2015-01-01"  # Earliest date to process (YYYY-MM-DD)
max_date = "2026-01-01"  # Latest date to process (YYYY-MM-DD)
export_database = true  # Export results to database file

[processing]
# Core processing parameters
extreme_threshold = 0.15   # Maximum deviation from Kalman prediction (0.20 = 20%)

[kalman]
# Kalman filter parameters (optimized 2025-09-13)
initial_variance = 0.361  # Initial state uncertainty
transition_covariance_weight = 0.016  # Process noise for weight
transition_covariance_trend = 0.0001  # Process noise for trend
observation_covariance = 3.4  # Measurement noise

# Reset configuration with different types
[kalman.reset.hard]
# Hard reset for 30+ day gaps (aggressive adaptation)
enabled = true
gap_threshold_days = 30
weight_boost_factor = 10
trend_boost_factor = 100
decay_rate = 3
warmup_measurements = 10
adaptive_days = 7
quality_threshold = 0.4

[kalman.reset.initial]
# Initial reset for first measurement (aggressive adaptation)
enabled = true
weight_boost_factor = 20
trend_boost_factor = 100
decay_rate = 3
warmup_measurements = 10
adaptive_days = 10
quality_threshold = 0.4

[kalman.reset.soft]
# Soft reset for manual data entry (gentle adaptation)
enabled = true
min_change_kg = 5  # Minimum weight change to trigger soft reset
cooldown_days = 3  # Days to wait before allowing another reset
weight_boost_factor = 3  # Gentler boost (vs 10 for hard)
trend_boost_factor = 10  # Gentler boost (vs 100 for hard)
decay_rate = 5  # Slower decay (vs 3 for hard)
warmup_measurements = 15  # Longer adaptation (vs 10 for hard)
adaptive_days = 10  # Longer period (vs 7 for hard)
quality_threshold = 0.5  # Less lenient (vs 0.4 for hard)
# Manual data sources that trigger soft reset
trigger_sources = ["questionnaire", "patient-upload", "care-team-upload"]


[kalman.post_reset_adaptation]
# Adaptive parameters for quick adaptation after reset
enabled = true  # Enable adaptive covariances after reset
warmup_measurements = 8 # Number of measurements to adapt over
weight_boost_factor = 20  # Initial multiplier for weight covariance
trend_boost_factor = 100 # Initial multiplier for trend covariance
decay_rate = 2  # Exponential decay rate (smaller = faster decay)

[visualization]
# Display settings
enabled = true  # Enable visualization output
use_enhanced = true  # Use enhanced dashboard with quality insights
verbosity = "normal"  # Verbosity level: "silent" | "minimal" | "normal" | "verbose"

[visualization.markers]
# Marker display configuration
show_source_icons = true  # Different marker shapes per source type
show_source_legend = true  # Display legend for source types
show_reset_markers = true  # Display reset event annotations
reset_marker_color = "#FF6600"  # Color for reset markers (orange)
reset_marker_opacity = 0.2  # Transparency of reset lines (0-1)
reset_marker_width = 1  # Width of reset lines in pixels
reset_marker_style = "dot"  # Line style: "solid" | "dash" | "dot"

[visualization.rejection]
# Rejection display configuration
show_severity_colors = true  # Color intensity shows rejection severity
group_by_severity = true  # Separate legend entries per severity level

[visualization.reset]
# Reset event display configuration
show_reset_lines = true  # Show vertical lines at reset points
show_gap_regions = true  # Shade the gap periods
show_gap_labels = true  # Display gap duration text
reset_line_color = "#FF6600"  # Orange for visibility
reset_line_style = "dash"  # Line style: "solid" | "dash" | "dot"
reset_line_width = 2  # Thickness in pixels
gap_region_color = "#F0F0F0"  # Light gray for gap regions
gap_region_opacity = 0.5  # Transparency (0-1)
gap_region_pattern = "diagonal"  # Pattern: "solid" | "diagonal" | "dots"
show_transition_markers = true  # Mark pre-gap and post-reset points
transition_marker_size = 10  # Size of special markers

[adaptive_noise]
# Adaptive noise configuration for source-specific processing
enabled = true  # Enable adaptive noise based on source type
default_multiplier = 1.5  # Default noise multiplier for unknown sources

[logging]
# Logging configuration
progress_interval = 10000  # Show progress every N rows
timestamp_format = "test_no_date"  # Format for output timestamps

[quality_scoring]
# Quality scoring system configuration
enabled = true  # Enable quality scoring system
threshold = 0.6  # Minimum score for acceptance (0-1)
use_harmonic_mean = true  # Use harmonic mean (penalizes low scores)

[quality_scoring.component_weights]
# Component weights (must sum to 1.0)
safety = 0.35        # Weight for physiological limits check
plausibility = 0.25  # Weight for statistical deviation check
consistency = 0.25   # Weight for rate of change check
reliability = 0.15   # Weight for source reliability check
