# Weight Stream Processor Configuration

[data]
# CSV file to process
csv_file = "./data/2025-09-05_optimized.csv"

# Output directory for results and visualizations
output_dir = "output"

# Maximum number of users to process (0 = unlimited)
max_users = 20

# Number of users to skip at the beginning (useful for resuming or testing)
user_offset = 400

# Minimum number of readings required to process a user (0 = no minimum)
# Users with fewer readings are skipped and don't count towards max_users
min_readings = 20



# List of specific user IDs to process
test_users = [
  "0040872d-333a-4ace-8c5a-b2fcd056e65a", # user with extremely noisy data
  "1e87d3ab-20b1-479d-ad4d-8986e1af38da", # long gap
  "0093a653-476b-4401-bbec-33a89abc2b18", # User with sparse historical data
  "4d5054c4-2492-4cd8-a15c-53381fb6bd49", # spiky data
  "1a452430-7351-4b8c-b921-4fb17f8a29cc", # single outlier should be rejected
  "5a4e195f-47d4-4f6e-aab4-1e29a1830e63", # some obvious outliers, some smaller outliers that should be rejected
  "3e3ca1f5-3a99-4bc4-93e0-80781d7749e2", # initial outlier, throws off all future data
  "77c8fbf5-2dca-419a-a602-93f47e3d5d84", # multiple initial outliers, throws off all future data
  "48f3ae0e-8688-4b15-8f30-537224646426", # good data before and after gap but big difference across gap
]

# 0040872d-333a-4ace-8c5a-b2fcd056e65a - user with extremely noisy data

[processing]
# min_init_readings = 10  # No longer used - immediate processing enabled

# Weight validation limits (kg)
min_weight = 30.0
max_weight = 400.0

# Maximum daily change allowed (as fraction)
max_daily_change = 0.05  # was 0.03

# Extreme deviation threshold for rejecting measurements
extreme_threshold = 0.20  # was 0.30

# Kalman-guided cleanup threshold (kg)
# Measurements more than this far from Kalman prediction are rejected during daily cleanup
kalman_cleanup_threshold = 4.0

[kalman]
# Initial variance scaling
initial_variance = 0.5  # was 1.0

# Process noise covariance matrix values
transition_covariance_weight = 0.05  # was 0.5
transition_covariance_trend = 0.0005  # was 0.01

# Observation noise
observation_covariance = 1.5  # was 1.0

# Reset threshold - days without data before resetting state
reset_gap_days = 30

[visualization]
# Dashboard settings
dashboard_dpi = 100
dashboard_figsize = [16, 10]

# Moving average window for trend analysis
moving_average_window = 7

# Time range for cropped views (in months)
# Shows the last N months of data for each user
cropped_months = 9

[physiological]
# Maximum weight changes by time period
# Based on framework document recommendations (Section 3.1)
# "daily fluctuations up to 2-3% of body weight"
# Adjusted to be less restrictive for legitimate weight loss scenarios

# Percentage limits for different time periods
max_change_1h_percent = 0.02     # 2% for < 1 hour (was 1.5%)
max_change_6h_percent = 0.025    # 2.5% for < 6 hours (was 2%)
max_change_24h_percent = 0.035   # 3.5% for ≤ 24 hours (framework says up to 3%, allowing slightly more)

# Absolute limits (kg) - raised to avoid over-rejection
max_change_1h_absolute = 3.0     # 3kg max for 1 hour (was 2.0)
max_change_6h_absolute = 4.0     # 4kg max for 6 hours (was 3.0)
max_change_24h_absolute = 5.0    # 5kg max for 24 hours (was 2.5, too restrictive)

# Long-term sustained change - increased for GLP-1 medications and diets
max_sustained_daily = 1.5         # 1.5kg/day for changes > 24 hours (was 0.5kg)
# Note: GLP-1 agonists can cause 1-2kg/week loss initially
# But we cap at 1.5kg/day to still catch errors while allowing aggressive weight loss

# Session detection for multi-user identification
session_timeout_minutes = 5.0     # Group measurements within 5 minutes
session_variance_threshold = 5.0  # kg - reject sessions with >5kg variance

# Tolerance for borderline cases
limit_tolerance = 0.10  # 10% buffer for short-term limits (< 24h)
sustained_tolerance = 0.25  # 25% buffer for sustained limits (> 24h) to allow weight loss patterns

# Enable graduated physiological limits
enable_physiological_limits = true

[logging]
# Progress update interval (rows)
progress_interval = 10000

# Date format for output files
# timestamp_format = "%Y%m%d_%H%M%S"
timestamp_format = "test_no_date"
