# User-Friendly Configuration Profiles
# Select a profile and optionally override specific settings
# This generates the full config.toml with appropriate parameters

# ============================================================================
# QUICK START - Choose ONE profile
# ============================================================================

active_profile = "balanced"  # Options: "conservative", "balanced", "aggressive", "clinical"

# ============================================================================
# SIMPLE CONTROLS - Most users only need these
# ============================================================================

[user_settings]
# Data source
input_file = "./data/2025-09-05_nocon.csv"
output_directory = "output"

# Processing scope
max_users_to_process = 20
minimum_readings_required = 20

# Date range (optional)
start_date = "2015-01-01"
end_date = "2026-01-01"

# Visualization
generate_charts = true
chart_detail_level = "normal"  # "minimal", "normal", "detailed"

# ============================================================================
# PROFILES - Pre-configured behavior patterns
# ============================================================================

[profiles.conservative]
description = "Strict filtering, rejects questionable data, slow to adapt"
filtering_strength = "strict"           # How aggressively to filter outliers
adaptation_speed = "slow"               # How quickly to accept new weight ranges
trust_manual_entries = "low"           # Trust level for user-reported weights
gap_sensitivity = "high"               # How sensitive to data gaps
quality_threshold = 0.7                # Minimum quality score to accept (70%)

[profiles.balanced]
description = "Default settings, moderate filtering, reasonable adaptation"
filtering_strength = "moderate"
adaptation_speed = "moderate"
trust_manual_entries = "moderate"
gap_sensitivity = "moderate"
quality_threshold = 0.6                # 60% threshold

[profiles.aggressive]
description = "Accepts most data, quick to adapt, minimal filtering"
filtering_strength = "lenient"
adaptation_speed = "fast"
trust_manual_entries = "high"
gap_sensitivity = "low"
quality_threshold = 0.45               # 45% threshold

[profiles.clinical]
description = "Healthcare setting: trusts clinical sources, strict on devices"
filtering_strength = "source_based"    # Different rules per source
adaptation_speed = "moderate"
trust_manual_entries = "clinical_only" # Only trust care-team entries
gap_sensitivity = "moderate"
quality_threshold = 0.55

# ============================================================================
# ADVANCED OVERRIDES - Optional fine-tuning
# ============================================================================

[advanced]
# Only modify if you need specific behavior not covered by profiles

# Outlier detection
extreme_deviation_percent = 15         # Max % deviation from expected (default: 15)

# Reset behavior
gap_threshold_days = 30                # Days before considering data "stale"
manual_entry_change_threshold_kg = 5   # Min weight change to trigger soft reset

# Source reliability (lower = more trusted)
[advanced.source_trust]
care_team_upload = 0.5
patient_upload = 0.7
questionnaire = 0.8
patient_device = 1.0
connectivehealth_io = 1.5
iglucose_com = 3.0

# ============================================================================
# PROFILE MAPPINGS - DO NOT MODIFY
# ============================================================================
# These translate profiles to actual config parameters

[mappings.filtering_strength]
strict = { extreme_threshold = 0.10, quality_threshold = 0.70 }
moderate = { extreme_threshold = 0.15, quality_threshold = 0.60 }
lenient = { extreme_threshold = 0.25, quality_threshold = 0.45 }
source_based = { extreme_threshold = 0.15, quality_threshold = 0.55 }

[mappings.adaptation_speed]
slow = { initial_adapt = 20, hard_adapt = 15, soft_adapt = 20, decay_rate = 4.0 }
moderate = { initial_adapt = 10, hard_adapt = 10, soft_adapt = 15, decay_rate = 2.5 }
fast = { initial_adapt = 5, hard_adapt = 5, soft_adapt = 10, decay_rate = 1.0 }

[mappings.trust_manual_entries]
low = { soft_reset_enabled = false }
moderate = { soft_reset_enabled = true, min_change = 5 }
high = { soft_reset_enabled = true, min_change = 3 }
clinical_only = { soft_reset_enabled = true, sources = ["care-team-upload"] }

[mappings.gap_sensitivity]
low = { gap_days = 45 }
moderate = { gap_days = 30 }
high = { gap_days = 21 }
