[data]
csv_file = "./test_user_0672.csv"
output_dir = "output_test_user"
max_users = 100
user_offset = 0
min_readings = 5
min_date = "2015-01-01"
max_date = "2025-09-05"
export_database = true

[processing]
extreme_threshold = 0.20
kalman_cleanup_threshold = 4.0

[kalman]
initial_variance = 0.361
transition_covariance_weight = 0.0160
transition_covariance_trend = 0.0001
observation_covariance = 3.490
reset_gap_days = 30
questionnaire_reset_days = 10

[visualization]
enabled = true
mode = "interactive"
use_enhanced = true
verbosity = "verbose"
theme = "plotly_white"

[adaptive_noise]
enabled = true
default_multiplier = 1.5

[logging]
progress_interval = 10000
timestamp_format = "test_no_date"

[quality_scoring]
enabled = true
threshold = 0.6
use_harmonic_mean = true

[quality_scoring.component_weights]
safety = 0.35
plausibility = 0.25
consistency = 0.25
reliability = 0.15
