# Weight Stream Processor Configuration

[data]
csv_file = "./data/2025-09-05_optimized.csv"
output_dir = "output"
max_users = 100
user_offset = 100
min_readings = 20
min_date = "2015-01-01"
max_date = "2025-09-05"
export_database = true

[processing]
# Core processing thresholds
extreme_threshold = 0.20  # Deviation threshold for Kalman filter
kalman_cleanup_threshold = 4.0  # Z-score for outlier removal

[kalman]
# Optimized parameters from evolutionary algorithm (2025-09-13)
initial_variance = 0.361
transition_covariance_weight = 0.0160
transition_covariance_trend = 0.0001
observation_covariance = 3.490
reset_gap_days = 30
questionnaire_reset_days = 10

[visualization]
enabled = true
mode = "interactive"  # "interactive" | "static"
use_enhanced = true  # Use enhanced dashboard with quality insights
verbosity = "auto"  # "silent" | "minimal" | "normal" | "verbose" | "auto"
theme = "plotly_white"
dashboard_figsize = [16, 10]
moving_average_window = 7
cropped_months = 24

[visualization.interactive]
enable_webgl = true
max_points_before_decimation = 10000
default_time_range = "3M"  # 1W, 1M, 3M, 1Y, All

[visualization.quality]
show_quality_scores = true
quality_color_scheme = "RdYlGn"  # Red-Yellow-Green
highlight_threshold_zone = true
threshold_buffer = 0.05  # Highlight zone around threshold
show_component_details = true

[visualization.export]
png_width = 1920
png_height = 1080
png_scale = 2  # For retina displays

[adaptive_noise]
enabled = true
default_multiplier = 1.5

[logging]
progress_interval = 10000
timestamp_format = "test_no_date"

[quality_scoring]
enabled = true  # Enable quality scoring system
threshold = 0.6  # Acceptance threshold
use_harmonic_mean = true  # Penalizes low component scores

[quality_scoring.component_weights]
# Weights must sum to 1.0
safety = 0.35        # Physiological limits check
plausibility = 0.25  # Statistical deviation check
consistency = 0.25   # Rate of change check
reliability = 0.15   # Source reliability check
