# Weight Stream Processor Configuration (Simplified)

[data]
csv_file = "./data/2025-09-05_optimized.csv"
output_dir = "output"
max_users = 100
user_offset = 0
min_readings = 20
min_date = "2024-11-01"
max_date = "2025-09-05"
export_database = true

[processing]
# Core thresholds only - physiological limits are now hard-coded
extreme_threshold = 0.20
kalman_cleanup_threshold = 4.0

[kalman]
# Optimized parameters from evolutionary algorithm (2025-09-13)
initial_variance = 0.361
transition_covariance_weight = 0.0160
transition_covariance_trend = 0.0001
observation_covariance = 3.490
reset_gap_days = 30
questionnaire_reset_days = 10

[visualization]
enabled = true
dashboard_dpi = 100
dashboard_figsize = [16, 10]
moving_average_window = 7
cropped_months = 24

[adaptive_noise]
enabled = true
default_multiplier = 1.5

[logging]
progress_interval = 10000
timestamp_format = "test_no_date"