version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weight-processor-dev"
s3_bucket = "weight-processor-artifacts"
s3_prefix = "weight-processor"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "weight-processor-staging"
s3_bucket = "weight-processor-artifacts"
s3_prefix = "weight-processor-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "weight-processor-prod"
s3_bucket = "weight-processor-artifacts"
s3_prefix = "weight-processor-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"