print("KALMAN FILTER PURPOSE:")
print("=" * 60)
print("1. SMOOTH noisy measurements (reduce sensor noise)")
print("2. ESTIMATE true weight from uncertain measurements")
print("3. TRACK trends over time")
print("4. PREDICT next likely weight")
print()
print("PHYSIOLOGICAL VALIDATION PURPOSE:")
print("=" * 60)
print("1. REJECT impossible measurements (e.g., 50kg gain in 1 hour)")
print("2. CATCH sensor errors (scale malfunction, unit errors)")
print("3. PROTECT Kalman from corrupted input")
print("4. ENSURE medical safety")
print()
print("THE KEY INSIGHT:")
print("=" * 60)
print("Physiological validation is a GATEKEEPER:")
print("- It runs BEFORE Kalman filtering")
print("- It protects the Kalman filter from garbage input")
print("- It asks: 'Is this raw measurement physically possible?'")
print()
print("Current Bug: Validation asks wrong question:")
print("- 'Is this raw measurement possible given the FILTERED history?'")
print("- This mixes two different realities!")
print()
print("The Fix: Validation asks the right question:")
print("- 'Is this raw measurement possible given the RAW history?'")
print("- Then Kalman smooths the validated raw data")
print()
print("EXAMPLE SCENARIO:")
print("-" * 60)
print("Day 1: Raw = 100kg, Filtered = 100kg")
print("Day 2: Raw = 99kg,  Filtered = 99.5kg (Kalman smooths)")
print("Day 3: Raw = 98kg,  Filtered = 99kg (Kalman smooths more)")
print("Day 4: Raw = 101kg (3kg jump from yesterday's raw)")
print()
print("Current (BROKEN) validation:")
print("  Compares: 101kg (raw) vs 99kg (filtered) = 2kg change")
print("  Might reject even though 98->101 is reasonable")
print()
print("Fixed validation:")
print("  Compares: 101kg (raw) vs 98kg (raw) = 3kg change")
print("  Accepts if within daily limits")
print("  Kalman then smooths to maybe 99.5kg")
