customTags:
  - "!Base64 scalar"
  - "!Cidr sequence"
  - "!FindInMap sequence"
  - "!GetAtt scalar"
  - "!GetAtt sequence"
  - "!GetAZs scalar"
  - "!ImportValue scalar"
  - "!Join sequence"
  - "!Select sequence"
  - "!Split sequence"
  - "!Sub scalar"
  - "!Sub sequence"
  - "!Ref scalar"
  - "!Equals sequence"
  - "!And sequence"
  - "!If sequence"
  - "!Not sequence"
  - "!Or sequence"
  - "!Condition scalar"
  - "!Transform mapping"
