source_file = "./2025-09-05_optimized.csv"
specific_user_ids = ["001adb56-40a5-4ef2-a092-e20915e0fb81"]
min_readings_per_user = 3
enable_kalman = true
enable_baseline_gaps = true
baseline_gap_threshold_days = 14
enable_visualization = false
enable_enhanced_validation = true
[logging]
level = "DEBUG"
stdout_level = "DEBUG"
