source_file = "./2025-09-05_optimized.csv"
output_dir = "output"
process_max_users = 0
min_readings_per_user = 3
enable_visualization = true
enable_kalman = true
enable_baseline = true
enable_baseline_gaps = true
baseline_gap_threshold_days = 30
baseline_window_days = 7
baseline_min_readings = 3
user_id_list = ["001adb56-40a5-4ef2-a092-e20915e0fb81"]

[logging]
stdout_level = "WARNING"
file_level = "DEBUG"
