# Weight Stream Processor Configuration

# Data source
source_file = "./2025-09-05_optimized.csv"

# Output settings
[output]
directory = "output"

# Processing settings
[processing]
max_users = 1000  # 0 for unlimited
min_init_readings = 20
validation_gamma = 3.0

# Test with specific problematic users only
test_users = [
    "0157fbc2-e4c2-4bd1-96c9-96d3962cacc7",  # Has Kalman state corruption (578kg spike)
    "0040872d-333a-4ace-8c5a-b2fcd056e65a",  # Has physiologically impossible changes
    "01677b8a-34c8-4678-8e36-1a8bd76f4bb4",  # Has extreme weight variations
    "0069687c-c1b2-420e-bfae-009a284d13fe",  # Has 95.2 -> 78.0 -> 89.8 jumps
    "010fbe98-e372-48ec-b46b-b99093b028ad",  # Has 108.1 -> 38.9 -> 112.6 data error
  "00e96965-7bc0-43e4-bafa-fb7a0b573cf3", # drop of 3kg for 2 values then back up
  "01e5b8da-7c51-458e-8219-ac2be94fda94", # huge gap then suddenly new values with big drop
  "03b792f9-b7e2-4e9c-b2aa-723236ce49b0", # small gap drop then back up -- still accepted
  "03c10a9f-97ae-472b-9fa1-4dc3e861a8f5", # cliff data, should not follow
  "03dde526-2eb9-4827-aa11-695ac2aa981c", # huge dip
  "04fb0c8e-27e7-4d6d-bda9-4b2803006d3a", # low-line of data, trend follows it
  "0cf8f33a-3206-479e-9603-6dbb99353c11", # E01 - data in quick succession, first is off but accepted, others that fit better are rejected by kalman
]
# Set to empty list [] to process all users
filter_test_users = true # Enable to only process users in test_users list

# Layer 1: Physiological Pre-filtering (before Kalman)
[processing.layer1]
enabled = true  # Enable physiological gates
min_weight = 25.0  # Minimum plausible weight (lowered for very small adults)
max_weight = 450.0  # Maximum weight (increased for edge cases)
max_daily_change_percent = 3.0  # Normal daily fluctuation limit
medical_mode_percent = 5.0  # Relaxed limit for medical interventions
normal_threshold_percent = 15.0  # Warning threshold for deviations
extreme_threshold_percent = 30.0  # Rejection threshold for extreme deviations

# Baseline establishment
[processing.baseline]
collection_days = 7
max_collection_days = 14
min_readings = 1  # Reduced to accept users with sparse data
iqr_multiplier = 1.5

# Robust Kalman filter with outlier protection (default)
[processing.kalman]
process_noise_weight = 0.5
process_noise_trend = 0.01
outlier_threshold = 3.0  # Moderate outliers (dampened update)
extreme_outlier_threshold = 5.0  # Extreme outliers (completely rejected)
innovation_window_size = 20  # Window for adaptive threshold calculation

# State reset triggers to prevent corruption
reset_gap_days = 30  # Reset state after gaps longer than this (days)
reset_deviation_threshold = 0.5  # Reset if prediction is off by more than 50%
physiological_min_weight = 40.0  # Minimum plausible human weight (kg)
physiological_max_weight = 300.0  # Maximum plausible human weight (kg)

# Logging configuration
[logging]
file = "output/logs/app.log"
level = "DEBUG"  # File captures everything
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
stdout_enabled = true
stdout_level = "WARNING"  # Reduced console verbosity for cleaner progress display

# Visualization settings
[visualization]
enabled = true
use_enhanced = true  # Use enhanced dashboard with all features
max_users = 10  # Maximum number of users to visualize
output_dir = "output/visualizations"
